import React from 'react';
import Head from 'next/head';

function HeadSEO() {
  return (
    <Head>
      <title>Ryna Web</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default HeadSEO;
