name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'releases/*'
env:
  NEXT_PUBLIC_API_HOST: https://ryna-backend-staging-mvy9g.ondigitalocean.app
jobs:
  # make sure build/ci work properly
  build:
    name: Install, lint, and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }} # Cache key based on os + hashed yarn.lock contents

      - name: Yarn install, lint
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          yarn
          yarn lint
      - name: Build
        run: yarn build

      - name: Typecheck
        run: |
          yarn tsc
